import './globals.css'
import type { Metadata } from 'next'
import React from 'react'

const defaultUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : 'http://localhost:3000'

export const metadata: Metadata = {
  metadataBase: new URL(defaultUrl),

  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className='max-h-screen- my-auto h-full text-base antialiased'
    >
      <body className='mx-auto'>{children}</body>
    </html>
  )
}
